# Generated by Django 5.0.6 on 2024-06-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_line',
            field=models.CharField(default='Comment', max_length=10),
        ),
    ]
