# Generated by Django 5.0.6 on 2024-06-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_comment_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perfect',
            field=models.CharField(default='Content', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_line',
            field=models.CharField(default='Comment', max_length=20),
        ),
    ]
