# Generated by Django 5.0.6 on 2024-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_comment_line_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='property_id',
            field=models.CharField(default='UNKNOWN', max_length=8),
        ),
    ]
