# Generated by Django 5.0.6 on 2024-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='property_id',
            field=models.IntegerField(default='', null=True),
        ),
    ]
